[package]
name = "noneset"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@embl.de>"]
publish = false
edition = "2018"
build = "nanoset/build.rs"

[build-dependencies]
built = "0.3.1"

[dependencies]
pyo3-built = "0.3.0"

[dependencies.pyo3]
version = "0.8.0"
features = ["extension-module"]

[lib]
crate-type = ["cdylib"]
path = "nanoset/lib.rs"
